import turtle

def draw_bear_face():
    screen = turtle.Screen()
    screen.setup(width=600, height=600)
    screen.bgcolor("white")

    bear = turtle.Turtle()
    bear.speed(1)

    # Cara (círculo grande)
    bear.penup()
    bear.goto(0, -200)
    bear.pendown()
    bear.color("#d2a679")
    bear.begin_fill()
    bear.circle(200)
    bear.end_fill()

    # Oreja izquierda (círculo grande y pequeño)
    bear.penup()
    bear.goto(-120, 100)
    bear.pendown()
    bear.color("#d2a679")
    bear.begin_fill()
    bear.circle(75)
    bear.end_fill()

    bear.penup()
    bear.goto(-120, 125)
    bear.pendown()
    bear.color("#8b4513")
    bear.begin_fill()
    bear.circle(50)
    bear.end_fill()

    # Oreja derecha (círculo grande y pequeño)
    bear.penup()
    bear.goto(120, 100)
    bear.pendown()
    bear.color("#d2a679")
    bear.begin_fill()
    bear.circle(75)
    bear.end_fill()

    bear.penup()
    bear.goto(120, 125)
    bear.pendown()
    bear.color("#8b4513")
    bear.begin_fill()
    bear.circle(50)
    bear.end_fill()

    # Ojo izquierdo (círculo blanco y negro)
    bear.penup()
    bear.goto(-70, 50)
    bear.pendown()
    bear.color("white")
    bear.begin_fill()
    bear.circle(30)
    bear.end_fill()

    bear.penup()
    bear.goto(-70, 60)
    bear.pendown()
    bear.color("black")
    bear.begin_fill()
    bear.circle(15)
    bear.end_fill()

    # Ojo derecho (círculo blanco y negro)
    bear.penup()
    bear.goto(70, 50)
    bear.pendown()
    bear.color("white")
    bear.begin_fill()
    bear.circle(30)
    bear.end_fill()

    bear.penup()
    bear.goto(70, 60)
    bear.pendown()
    bear.color("black")
    bear.begin_fill()
    bear.circle(15)
    bear.end_fill()

    # Nariz (elipse negra)
    bear.penup()
    bear.goto(0, 0)
    bear.pendown()
    bear.color("black")
    bear.begin_fill()
    bear.circle(20)
    bear.end_fill()

    # Boca (líneas)
    bear.penup()
    bear.goto(0, -20)
    bear.pendown()
    bear.right(90)
    bear.forward(30)
    bear.penup()
    bear.goto(0, -50)
    bear.pendown()
    bear.right(45)
    bear.forward(20)
    bear.penup()
    bear.goto(0, -50)
    bear.pendown()
    bear.left(90)
    bear.forward(20)

    turtle.done()

# Llamar a la función para dibujar la cara del osito
draw_bear_face()

##